version: "3"
services: 

# BANCOS

  # sales-db:
  #   image: mongo:latest
  #   container_name: sales-db
  #   restart: always
  #   networks:
  #     - sales-network
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=123456
  #   ports:
  #     - 27017:27017
  #     - 28017:28017

  auth-db:
    image: postgres:11
    container_name: auth-db
    restart: always
    networks:
      - sales-network
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=suplament
      - POSTGRES_PASSWORD=suplament123
    ports:
      - 5432:5432

  # sales_rabbit:
  #   image: rabbitmq:3-management
  #   container_name: sales_rabbit
  #   hostname: sales_rabbit
  #   networks:
  #     - sales-network
  #   ports:
  #     - 5672:5672
  #     - 25676:25676
  #     - 15672:15672
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest

  suplament-db:
    image: postgres:11
    container_name: suplament-db
    restart: always
    networks:
      - sales-network
    environment:
      - POSTGRES_DB=suplament-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5434:5432

# APIS

  suplament-api:
    build: './suplament-api'
    container_name: suplament-api
    depends_on:
      - suplament-db
      - sales_rabbit
    networks:
      - sales-network
    environment:
      - PORT=8081
      - API_SECRET=YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0xMjM0NTY=
      - DB_HOST=suplament-db
      - DB_NAME=suplament-db
      - DB_USER=suplament
      - DB_PASSWORD=suplament123
      - DB_PORT=5434
      - RABBIT_MQ_HOST=sales_rabbit
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER=guest
      - RABBIT_MQ_PASSWORD=guest
      - SALES_HOST=sales-api
      - SALES_PORT=8082
    ports:
      - 8080:8080

  # sales-api:
  #   build: './sales-api'
  #   container_name: sales-api
  #   depends_on:
  #     - sales-db
  #     - sales_rabbit
  #     - suplament-api
  #   networks:
  #     - sales-network
  #   environment:
  #     - PORT=8082
  #     - API_SECRET=YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0xMjM0NTY=
  #     - MONGO_DB_URL=mongodb://admin:123456@sales-db:27017/
  #     - RABBIT_MQ_URL=amqp://guest:guest@sales_rabbit:5672/
  #     - SUPLAMENT_API_URL=http://suplament-api:8081/api/suplament
  #     - NODE_ENV=container
  #   ports:
  #     - 8082:8082

  auth-api:
    build: './auth-api'
    container_name: auth-api
    depends_on:
      - auth-db
      - suplament-api
    networks:
      - sales-network
    environment:
      - PORT=8081
      - API_SECRET=YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0xMjM0NTY=
      - DB_HOST=auth-db
      - DB_NAME=auth-db
      - DB_USER=suplament
      - DB_PASSWORD=suplament123
      - DB_PORT=5432
      - NODE_ENV=container
    ports:
      - 8081:8081

networks:
  sales-network:
    driver: bridge