--CREATE TABLE usuario (
--    id                       bigint NOT NULL,
--    active                   boolean NOT NULL,
--    email                    VARCHAR(255) NOT NULL,
--    senha                    VARCHAR(255) NOT NULL,
--    telefone                 VARCHAR(255),
--    grupo                    boolean NOT NULL,
--    endereco_id              bigint,
--    PRIMARY KEY (id),
--    FOREIGN KEY (endereco_id) REFERENCES endereco(id)
--);
